// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/gasto_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 4104996196160142625),
      name: 'GastoModel',
      lastPropertyId: const IdUid(6, 8925070702863642642),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2859077283631563039),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 7208498870002418812),
            name: 'nombreGasto',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5403876232334322867),
            name: 'descripcionGasto',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1297030238003407958),
            name: 'cantidadGasto',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 5910646345707319900),
            name: 'categoriaGasto',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 8925070702863642642),
            name: 'fechaGasto',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 4104996196160142625),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    GastoModel: EntityDefinition<GastoModel>(
        model: _entities[0],
        toOneRelations: (GastoModel object) => [],
        toManyRelations: (GastoModel object) => {},
        getId: (GastoModel object) => object.id,
        setId: (GastoModel object, int id) {
          object.id = id;
        },
        objectToFB: (GastoModel object, fb.Builder fbb) {
          final nombreGastoOffset = fbb.writeString(object.nombreGasto);
          final descripcionGastoOffset =
              fbb.writeString(object.descripcionGasto);
          final categoriaGastoOffset = fbb.writeString(object.categoriaGasto);
          final fechaGastoOffset = fbb.writeString(object.fechaGasto);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nombreGastoOffset);
          fbb.addOffset(2, descripcionGastoOffset);
          fbb.addInt64(3, object.cantidadGasto);
          fbb.addOffset(4, categoriaGastoOffset);
          fbb.addOffset(5, fechaGastoOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = GastoModel(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              nombreGasto: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              descripcionGasto: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              cantidadGasto:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              categoriaGasto: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              fechaGasto: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, ''));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [GastoModel] entity fields to define ObjectBox queries.
class GastoModel_ {
  /// see [GastoModel.id]
  static final id =
      QueryIntegerProperty<GastoModel>(_entities[0].properties[0]);

  /// see [GastoModel.nombreGasto]
  static final nombreGasto =
      QueryStringProperty<GastoModel>(_entities[0].properties[1]);

  /// see [GastoModel.descripcionGasto]
  static final descripcionGasto =
      QueryStringProperty<GastoModel>(_entities[0].properties[2]);

  /// see [GastoModel.cantidadGasto]
  static final cantidadGasto =
      QueryIntegerProperty<GastoModel>(_entities[0].properties[3]);

  /// see [GastoModel.categoriaGasto]
  static final categoriaGasto =
      QueryStringProperty<GastoModel>(_entities[0].properties[4]);

  /// see [GastoModel.fechaGasto]
  static final fechaGasto =
      QueryStringProperty<GastoModel>(_entities[0].properties[5]);
}
